create table USER (
  ID INTEGER not null generated by default as identity (start with 42),
  ACCOUNT varchar(255) not null,
  PASSWORD  varchar(255) not null,
  EMAIL varchar(255),
  ROLE varchar(32) not null,
  CREATED timestamp not null,
  LAST_LOGIN timestamp not null,
  TAGS varchar(16M), -- e.g. HERDER-GYMNASIUM KÖLN Q1 ED_SHEERAN
  
  primary key (ID)
);

create unique index accountIdx on USER(ACCOUNT);

create table PROGRAM (
  ID INTEGER not null generated by default as identity (start with 42),
  NAME varchar(255) not null,
  OWNER_ID INTEGER not null,
  PROGRAM_TEXT varchar(16M),
  CREATED timestamp not null,
  LAST_CHANGED timestamp not null,
  LAST_CHECKED timestamp,
  LAST_ERRORFREE timestamp,
  NUMBER_OF_BLOCKS INTEGER,
  TAGS varchar(16M), -- e.g. CAR AUTONOMOUS COOL 3WHEELS
  ICON_NUMBER integer not null,
  
  primary key (ID),
  foreign key (OWNER_ID) references USER(ID) ON DELETE CASCADE
);

create unique index progNameOwnerIdx on PROGRAM(NAME, OWNER_ID);

create table USER_PROGRAM (
  ID INTEGER not null generated by default as identity (start with 42),
  USER_ID INTEGER not null,
  PROGRAM_ID INTEGER not null,
  RELATION varchar(32) not null, -- 1 READ access, 2 WRITE access, 4 DELETE right, (really? not yet used) 8 PROMOTE_READ right, 16 PROMOTE_WRITE right
 
  foreign key (USER_ID) references USER(ID) ON DELETE CASCADE,
  foreign key (PROGRAM_ID) references PROGRAM(ID) ON DELETE CASCADE
);

create table CONFIGURATION (
  ID INTEGER not null generated by default as identity (start with 42),
  NAME varchar(255) not null,
  OWNER_ID INTEGER,
  CONFIGURATION_TEXT varchar(16M),
  CREATED timestamp not null,
  LAST_CHANGED timestamp not null,
  LAST_CHECKED timestamp,
  LAST_ERRORFREE timestamp,
  TAGS varchar(16M), -- e.g. CAR AUTONOMOUS COOL 3WHEELS
  ICON_NUMBER integer not null,
  
  primary key (ID),
  foreign key (OWNER_ID) references USER(ID) ON DELETE CASCADE
);

create unique index confNameOwnerIdx on CONFIGURATION(NAME, OWNER_ID);

insert into CONFIGURATION
( NAME, OWNER_ID, CONFIGURATION_TEXT, CREATED, LAST_CHANGED, LAST_CHECKED, LAST_ERRORFREE, TAGS, ICON_NUMBER )
values ('Standardkonfiguration', null, 
        '<block_set xmlns=''http://de.fhg.iais.roberta.blockly''><instance x=''1'' y=''1''><block id=''1'' type=''robBrick_EV3-Brick''><field name="WHEEL_DIAMETER">5.6</field><field name="TRACK_WIDTH">17</field><value name=''S1''><block id=''2'' type=''robBrick_touch''/></value><value name=''S4''><block id=''3'' type=''robBrick_ultrasonic''/></value><value name=''MB''><block id=''4'' type=''robBrick_motor_big''><field name=''MOTOR_REGULATION''>TRUE</field><field name=''MOTOR_REVERSE''>OFF</field><field name=''MOTOR_DRIVE''>RIGHT</field></block></value><value name=''MC''><block id=''5'' type=''robBrick_motor_big''><field name=''MOTOR_REGULATION''>TRUE</field><field name=''MOTOR_REVERSE''>OFF</field><field name=''MOTOR_DRIVE''>LEFT</field></block></value></block></instance></block_set>',
	    now, now, now, now,
	    '', 0
	   );

commit;

